backend:
  name: git-gateway
  branch: main

media_folder: "static/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "avantapres"
    label: "Avant/Après"
    folder: "content/avantapres"  # dossier où seront stockés les fichiers
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Titre", name: "title", widget: "string" }
      - { label: "Image Avant", name: "imageAvant", widget: "image" }
      - { label: "Image Après", name: "imageApres", widget: "image" }
      - { label: "Description", name: "description", widget: "text", required: false }
