backend:
  name: git-gateway
  branch: main  # Votre branche principale

media_folder: "static/images/uploads" # Dossier où seront stockées les images
public_folder: "/images/uploads"      # Chemin public pour accéder aux images

collections:
  - name: "gallery"
    label: "Galerie"
    folder: "content/gallery"  
    create: true
    fields:
      - { label: "Titre", name: "title", widget: "string" }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Description", name: "description", widget: "text" }
