backend:
  name: github
  repo: Fredchanu/CL-végétal-design  # Remplace par ton dépôt GitHub
  branch: main

media_folder: "static/images/uploads"
public_folder: "/static/images/uploads"

collections:
  - name: "avantapres"
    label: "Avant/Après"
    files:
      - file: "data/avantapres.json"
        label: "Galerie Avant/Après"
        name: "avantapres"
        fields:
          - { label: "Entrées", name: "entries", widget: "list", field: {
                label: "Item",
                name: "item",
                widget: "object",
                fields: [
                  { label: "Titre", name: "title", widget: "string" },
                  { label: "Image Avant", name: "imageAvant", widget: "image" },
                  { label: "Image Après", name: "imageApres", widget: "image" },
                  { label: "Description", name: "description", widget: "text", required: false }
                ]
              }
            }
